[package]
name = "pyo3-bond-pricing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyo3_bond_pricing"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
